# This workflow file generates binaries for both Windows
# and OS X.  However, https://github.com/actions/upload-artifact/issues/38
# that basically says that it won't ever preserve permissions.
# That means an archive in an archive since we need to preserve them
# on OS X.  Still... better than doing this all by hand.

---

name: pyinstaller

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  pyinstaller-mac:
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python3 -m venv /tmp/venv
          source /tmp/venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: pyinstaller
        run: |
          cd Serato-Now-Playing
          cp resources/SeratoNowPlaying_MAC.spec SeratoNowPlaying_MAC.spec
          /tmp/venv/bin/pyinstaller -w SeratoNowPlaying_MAC.spec
      - name: manipulate the dist
        run: |
          pwd
          cd Serato-Now-Playing/dist
          zip -r SeratoNowPlaying.zip SeratoNowPlaying.app
          rm -rf SeratoNowPlaying SeratoNowPlaying.app
      - name: artifact dist
        uses: actions/upload-artifact@v2
        with:
          name: mac-dist
          path: Serato-Now-Playing/dist/

  pyinstaller-win:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: stuff
        run: pwd
      - name: pyinstaller
        run: |
          cd Serato-Now-Playing
          COPY resources\\SeratoNowPlaying_WIN.spec SeratoNowPlaying_WIN.spec
          pyinstaller -F -w SeratoNowPlaying_WIN.spec
      - name: artifact dist
        uses: actions/upload-artifact@v2
        with:
          name: win-dist
          path: Serato-Now-Playing\\dist\\SeratoNowPlaying.exe
