# This workflow file generates binaries for both Windows
# and OS X.  However, https://github.com/actions/upload-artifact/issues/38
# that basically says that it won't ever preserve permissions.
# That means an archive in an archive since we need to preserve them
# on OS X.  Still... better than doing this all by hand.

---

name: serato-reader

on: [push]  # yamllint disable-line rule:truthy

jobs:
  serato-mac:
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python3 -m venv /tmp/venv
          source /tmp/venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install .
      - name: run-serato-2.5-win
        run: |
          source /tmp/venv/bin/activate
          touch test/*/*
          python3 nowplaying/inputs/serato.py test/serato-2.5-win/
      - name: run-serato-2.4-mac
        run: |
          source /tmp/venv/bin/activate
          python3 nowplaying/inputs/serato.py test/serato-2.4-mac/


  serato-win:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: update tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: run-serato-2.5-win
        run: |
          touch test/*/*
          python3 nowplaying/inputs/serato.py test/serato-2.5-win/
      - name: run-serato-2.4-mac
        run: |
          python3 nowplaying/inputs/serato.py test/serato-2.4-mac/
